<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RQ3L8BF" failures="0" tests="15" name="tests.AgentSignUp" time="117.819" errors="1" timestamp="2022-01-05T20:47:26 IST" skipped="1">
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldGet_TheValidationError_InCaseOfEmptyFields" time="10.426"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_Should_GetError_OnEnter_InvalidNumber" time="5.254"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_Should_GetError_OnEnter_InvalidEmail" time="8.473"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_Should_GetError_OnEnter_AlreadyExistUser" time="13.095"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldNot_AbleToEnter_AlphabeticalValue_inMobileNumber_Field" time="1.652"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_Should_ValidateFirstForm_InCaseOfValidFields" time="24.153"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldGet_TheValidationError_InCaseOfEmptyFields_Step2" time="6.828"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldbeAble_ToUpload_ImageSuccessfully" time="9.311"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldbeAble_ToSelect_YearSuccessfully" time="5.288"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldbeAble_ToSelect_Town_Successfully" time="9.099"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldbeAble_ToSubmit_Step2_Successfully" time="4.520"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldbeAble_ToReachOn_Step3_Successfully" time="3.311">
    <error message="element click intercepted: Element &lt;button class=&quot;btn btn__btn btn-dark&quot;&gt;...&lt;/button&gt; is not clickable at point (1429, 24). Other element would receive the click: &lt;div class=&quot;ant-spin-spinning&quot;&gt;...&lt;/div&gt;
  (Session info: chrome=96.0.4664.110)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:25:48&#039;
System info: host: &#039;DESKTOP-RQ3L8BF&#039;, ip: &#039;192.168.1.5&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 96.0.4664.110, chrome: {chromedriverVersion: 96.0.4664.18 (b8887b3d1742a..., userDataDir: C:\Users\khans\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:64387}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: f73849094afbf20556fed1971319544e" type="org.openqa.selenium.ElementClickInterceptedException">
      <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <button class="btn btn__btn btn-dark">...</button> is not clickable at point (1429, 24). Other element would receive the click: <div class="ant-spin-spinning">...</div>
  (Session info: chrome=96.0.4664.110)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-RQ3L8BF', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 96.0.4664.110, chrome: {chromedriverVersion: 96.0.4664.18 (b8887b3d1742a..., userDataDir: C:\Users\khans\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:64387}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: f73849094afbf20556fed1971319544e
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at tests.AgentSignUp.TC_Negative_Verify_that_Agent_ShouldbeAble_ToReachOn_Step3_Successfully(AgentSignUp.java:438)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC_Negative_Verify_that_Agent_ShouldbeAble_ToReachOn_Step3_Successfully -->
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldGet_TheValidationError_InCaseOfEmptyFields_Step3" time="6.268"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_Should_SignUp_Successfully_AfterStep3" time="10.141"/>
  <system-out/>
  <testcase classname="tests.AgentSignUp" name="TC_Negative_Verify_that_Agent_ShouldbeAble_ToUpload_ValidImageSuccessfully">
    <skipped/>
  </testcase> <!-- TC_Negative_Verify_that_Agent_ShouldbeAble_ToUpload_ValidImageSuccessfully -->
  <system-out/>
</testsuite> <!-- tests.AgentSignUp -->
